// flow-typed signature: 9a59d138ec895255e702359257c3df21
// flow-typed version: <<STUB>>/babel-preset-babili_v^0.0.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-babili'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-babili' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-babili/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-babili/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-babili/lib/index'>;
}
