// flow-typed signature: 6ff87271d85ef5850e14724407520119
// flow-typed version: <<STUB>>/eslint-config-exponent_v^4.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-exponent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-exponent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-exponent/eslintrc' {
  declare module.exports: any;
}

declare module 'eslint-config-exponent/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-exponent/eslintrc.js' {
  declare module.exports: $Exports<'eslint-config-exponent/eslintrc'>;
}
declare module 'eslint-config-exponent/react.js' {
  declare module.exports: $Exports<'eslint-config-exponent/react'>;
}
