// flow-typed signature: ee7f5afea8b6db81fc899714c446be0d
// flow-typed version: <<STUB>>/git-info-async_v^1.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-info-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-info-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'git-info-async/index' {
  declare module.exports: $Exports<'git-info-async'>;
}
declare module 'git-info-async/index.js' {
  declare module.exports: $Exports<'git-info-async'>;
}
