// flow-typed signature: e3fd7e267718e2754572e59a4fff04f3
// flow-typed version: <<STUB>>/gulplog_v^1.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulplog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulplog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulplog/index' {
  declare module.exports: $Exports<'gulplog'>;
}
declare module 'gulplog/index.js' {
  declare module.exports: $Exports<'gulplog'>;
}
