// flow-typed signature: 1a0039eb79f460c560a0e882a6db79be
// flow-typed version: <<STUB>>/gulp-watch_v^4.3.6/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-watch/index' {
  declare module.exports: $Exports<'gulp-watch'>;
}
declare module 'gulp-watch/index.js' {
  declare module.exports: $Exports<'gulp-watch'>;
}
