// flow-typed signature: c1e50b5ca82b26ede3fbc2c6fa4d5bd9
// flow-typed version: <<STUB>>/promise-print_v^2.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'promise-print/index' {
  declare module.exports: $Exports<'promise-print'>;
}
declare module 'promise-print/index.js' {
  declare module.exports: $Exports<'promise-print'>;
}
