// flow-typed signature: 919279e91358306d3150147100a38ecf
// flow-typed version: <<STUB>>/react-linkify_v^0.1.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-linkify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-linkify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-linkify/dist/Linkify' {
  declare module.exports: any;
}

declare module 'react-linkify/src/__tests__/Linkify-test' {
  declare module.exports: any;
}

declare module 'react-linkify/src/Linkify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-linkify/dist/Linkify.js' {
  declare module.exports: $Exports<'react-linkify/dist/Linkify'>;
}
declare module 'react-linkify/src/__tests__/Linkify-test.js' {
  declare module.exports: $Exports<'react-linkify/src/__tests__/Linkify-test'>;
}
declare module 'react-linkify/src/Linkify.jsx' {
  declare module.exports: $Exports<'react-linkify/src/Linkify'>;
}
