// flow-typed signature: 1f4d0ead9ca71d75221b1a8d6ac1f33c
// flow-typed version: <<STUB>>/redux-actions_v^0.12.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-actions/dist/redux-actions' {
  declare module.exports: any;
}

declare module 'redux-actions/dist/redux-actions.min' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/combineActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/index' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/ownKeys' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-actions/dist/redux-actions.js' {
  declare module.exports: $Exports<'redux-actions/dist/redux-actions'>;
}
declare module 'redux-actions/dist/redux-actions.min.js' {
  declare module.exports: $Exports<'redux-actions/dist/redux-actions.min'>;
}
declare module 'redux-actions/lib/combineActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/combineActions'>;
}
declare module 'redux-actions/lib/createAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/createAction'>;
}
declare module 'redux-actions/lib/createActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/createActions'>;
}
declare module 'redux-actions/lib/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleAction'>;
}
declare module 'redux-actions/lib/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleActions'>;
}
declare module 'redux-actions/lib/index.js' {
  declare module.exports: $Exports<'redux-actions/lib/index'>;
}
declare module 'redux-actions/lib/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/lib/ownKeys'>;
}
