// flow-typed signature: cd0bf8230d5acdb18f2280d38c93a92d
// flow-typed version: <<STUB>>/redux-promise-middleware_v^4.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise-middleware/dist/index' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/ReduxPromiseMiddleware' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/ReduxPromiseMiddleware.min' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise-middleware/dist/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/index'>;
}
declare module 'redux-promise-middleware/dist/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/isPromise'>;
}
declare module 'redux-promise-middleware/dist/ReduxPromiseMiddleware.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/ReduxPromiseMiddleware'>;
}
declare module 'redux-promise-middleware/dist/ReduxPromiseMiddleware.min.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/ReduxPromiseMiddleware.min'>;
}
declare module 'redux-promise-middleware/webpack.config.js' {
  declare module.exports: $Exports<'redux-promise-middleware/webpack.config'>;
}
