// flow-typed signature: bd2d74ce55d6b7cffec382600276ab6a
// flow-typed version: <<STUB>>/webpack-node-externals_v^1.5.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-node-externals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-node-externals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-node-externals/index' {
  declare module.exports: $Exports<'webpack-node-externals'>;
}
declare module 'webpack-node-externals/index.js' {
  declare module.exports: $Exports<'webpack-node-externals'>;
}
