// flow-typed signature: 25a4da3ff526b29b76351145f21dc1ff
// flow-typed version: <<STUB>>/@exponent/electron-cookies_v^2.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@exponent/electron-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@exponent/electron-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@exponent/electron-cookies/cookies' {
  declare module.exports: any;
}

// Filename aliases
declare module '@exponent/electron-cookies/cookies.js' {
  declare module.exports: $Exports<'@exponent/electron-cookies/cookies'>;
}
