// flow-typed signature: 6b4283eea023a972f304136e24e53a13
// flow-typed version: <<STUB>>/@exponent/json-file_v^5.0.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@exponent/json-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@exponent/json-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@exponent/json-file/__tests__/JsonFile-test' {
  declare module.exports: any;
}

declare module '@exponent/json-file/__tests__/JsonFileError-test' {
  declare module.exports: any;
}

declare module '@exponent/json-file/jest/preprocessor' {
  declare module.exports: any;
}

declare module '@exponent/json-file/JsonFile' {
  declare module.exports: any;
}

declare module '@exponent/json-file/JsonFileError' {
  declare module.exports: any;
}

// Filename aliases
declare module '@exponent/json-file/__tests__/JsonFile-test.js' {
  declare module.exports: $Exports<'@exponent/json-file/__tests__/JsonFile-test'>;
}
declare module '@exponent/json-file/__tests__/JsonFileError-test.js' {
  declare module.exports: $Exports<'@exponent/json-file/__tests__/JsonFileError-test'>;
}
declare module '@exponent/json-file/jest/preprocessor.js' {
  declare module.exports: $Exports<'@exponent/json-file/jest/preprocessor'>;
}
declare module '@exponent/json-file/JsonFile.js' {
  declare module.exports: $Exports<'@exponent/json-file/JsonFile'>;
}
declare module '@exponent/json-file/JsonFileError.js' {
  declare module.exports: $Exports<'@exponent/json-file/JsonFileError'>;
}
