// flow-typed signature: 8e1f9d4f99829afa5295a58855fdb9c6
// flow-typed version: <<STUB>>/@exponent/spawn-async_v^1.2.5/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@exponent/spawn-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@exponent/spawn-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@exponent/spawn-async/build/spawnAsync' {
  declare module.exports: any;
}

// Filename aliases
declare module '@exponent/spawn-async/build/spawnAsync.js' {
  declare module.exports: $Exports<'@exponent/spawn-async/build/spawnAsync'>;
}
