// flow-typed signature: 62cdedc99c7c6e35fe39fa5ea551d18b
// flow-typed version: <<STUB>>/@ccheever/crayon_v^5.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ccheever/crayon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@ccheever/crayon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ccheever/crayon/ansi256css' {
  declare module.exports: any;
}

declare module '@ccheever/crayon/crayon' {
  declare module.exports: any;
}

declare module '@ccheever/crayon/jest-preprocessor' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ccheever/crayon/ansi256css.js' {
  declare module.exports: $Exports<'@ccheever/crayon/ansi256css'>;
}
declare module '@ccheever/crayon/crayon.js' {
  declare module.exports: $Exports<'@ccheever/crayon/crayon'>;
}
declare module '@ccheever/crayon/jest-preprocessor.js' {
  declare module.exports: $Exports<'@ccheever/crayon/jest-preprocessor'>;
}
